// file config
let configObj = {
  // sheet config
  Sheet1: {
    // column config
    库位号: {
      required: true,
      pattern: /^[A-Z]{1,2}[0-9]+$/,
      minLength: 5,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      include: undefined,
      norepeat: true,
    },
    区域: {
      required: true,
      pattern: /^[A-Z]{1,2}[0-9]*/,
      minLength: 2,
      maxLength: 20,
      length: undefined,
      min: 1,
      max: 9,
      format: undefined,
      validator: undefined,
      include: undefined,
      norepeat: undefined,
    },
    通道: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      include: undefined,
      norepeat: undefined,
    },
    组: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      include: undefined,
      norepeat: undefined,
    },
    层: {
      required: true,
      pattern: /[A-Z0-9]/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: "number",
      validator: undefined,
      include: undefined,
      norepeat: undefined,
    },
    状态: {
      required: true,
      pattern: undefined,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      include: ["启用", "停用"],
      norepeat: undefined,
    },
  },
  Sheet2: {
    // column config
    库位号: {
      required: true,
      pattern: /^[A-Z]{1,2}[0-9]+$/,
      minLength: 5,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: function(cell,validate){
        if (!/^[A-Z]{1,2}[0-9]{3,7}$/.test(cell)) {
          validate.pattern = false;
        }
      },
      include: undefined,
      norepeat: undefined,
    },
    区域: {
      required: true,
      pattern: /^[A-Z]{1,2}[0-9]*/,
      minLength: 2,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      include: undefined,
      norepeat: undefined,
    },
    通道: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      include: undefined,
      norepeat: undefined,
    },
    组: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: undefined,
      maxLength: undefined,
      length: 2,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      include: undefined,
      norepeat: undefined,
    },
    层: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: "number",
      validator: undefined,
      include: undefined,
      norepeat: undefined,
    },
    状态: {
      required: true,
      pattern: undefined,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      include: ["启用", "停用"],
      norepeat: undefined,
    },
  },
};