// file config
let configObj = {
  // sheet config
  Sheet1: {
    // column config
    库位号: {
      required: true,
      pattern: /^[A-Z]{1,2}[0-9]+$/,
      minLength: 5,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      includs: undefined,
    },
    区域: {
      required: true,
      pattern: /^[A-Z]{1,2}[0-9]*/,
      minLength: 2,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      includs: undefined,
    },
    通道: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      includs: undefined,
    },
    组: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      includs: undefined,
    },
    层: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: "number",
      validator: undefined,
      includs: undefined,
    },
  },
  Sheet2: {
    // column config
    库位号: {
      required: true,
      pattern: /^[A-Z]{1,2}[0-9]+$/,
      minLength: 5,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      includs: undefined,
    },
    区域: {
      required: true,
      pattern: /^[A-Z]{1,2}[0-9]*/,
      minLength: 2,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      includs: undefined,
    },
    通道: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      includs: undefined,
    },
    组: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: undefined,
      validator: undefined,
      includs: undefined,
    },
    层: {
      required: true,
      pattern: /[0-9A-Z]+/,
      minLength: 1,
      maxLength: 20,
      length: undefined,
      min: undefined,
      max: undefined,
      format: "number",
      validator: undefined,
      includs: undefined,
    },
  },
};